### ISSUE TITLE
无颜之月

### ISSUE THREAD

**Issue by staciaa123** [HIllya51/some_vn_text#1]
我可以问一下如何将 .txt 文件打包成 .scw 文件吗？

**Comment by HIllya51** [comment]
额，我不是这作的汉化组的，这个纯提取着玩的，手里没有现成的写回代码，你要用就参考[提取](https://github.com/HIllya51/some_vn_text/tree/main/Kao%20no%20nai%20Tsuki/scwextract)逆着写呗。
